package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.82

import (
	"back-end/graph/model"
	"context"
	"fmt"
)

// TpSummary is the resolver for the tpSummary field.
func (r *queryResolver) TpSummary(ctx context.Context, year int32, wilaya string, commune *string) (*model.TPSummary, error) {
	if r.DashboardService == nil {
		return nil, fmt.Errorf("dashboard service is not configured")
	}

	var communeValue string
	if commune != nil {
		communeValue = *commune
	}

	summary, err := r.DashboardService.TpSummary(ctx, int(year), wilaya, communeValue)
	if err != nil {
		return nil, err
	}

	return &model.TPSummary{
		TotalGenere: clampToInt32(summary.TotalGenere),
		TotalSolde:  clampToInt32(summary.TotalSolde),
	}, nil
}

// TpByMonth is the resolver for the tpByMonth field.
func (r *queryResolver) TpByMonth(ctx context.Context, year int32, wilaya string, commune *string) ([]*model.TPByMonth, error) {
	if r.DashboardService == nil {
		return nil, fmt.Errorf("dashboard service is not configured")
	}

	var communeValue string
	if commune != nil {
		communeValue = *commune
	}

	stats, err := r.DashboardService.TpByMonth(ctx, int(year), wilaya, communeValue)
	if err != nil {
		return nil, err
	}

	result := make([]*model.TPByMonth, 0, len(stats))
	for _, stat := range stats {
		result = append(result, &model.TPByMonth{
			Month:    stat.Month.String(),
			TpGenere: clampToInt32(stat.TpGenere),
			TpSolde:  clampToInt32(stat.TpSolde),
		})
	}
	return result, nil
}

// InsuredUsers is the resolver for the insuredUsers field.
func (r *queryResolver) InsuredUsers(ctx context.Context, wilaya *string, commune *string) ([]*model.InsuredUser, error) {
	if r.DashboardService == nil {
		return nil, fmt.Errorf("dashboard service is not configured")
	}

	var wilayaValue, communeValue string
	if wilaya != nil {
		wilayaValue = *wilaya
	}
	if commune != nil {
		communeValue = *commune
	}

	records, err := r.DashboardService.InsuredUsers(ctx, wilayaValue, communeValue, 0)
	if err != nil {
		return nil, err
	}

	users := make([]*model.InsuredUser, 0, len(records))
	for _, record := range records {
		users = append(users, mapInsuredUser(record))
	}
	return users, nil
}

// FilterOptions is the resolver for the filterOptions field.
func (r *queryResolver) FilterOptions(ctx context.Context) (*model.FilterOptions, error) {
	if r.DashboardService == nil {
		return nil, fmt.Errorf("dashboard service is not configured")
	}

	options, err := r.DashboardService.FilterOptions(ctx)
	if err != nil {
		return nil, err
	}

	years := make([]int32, 0, len(options.Years))
	for _, year := range options.Years {
		years = append(years, int32(year))
	}

	return &model.FilterOptions{
		Years:    years,
		Communes: append([]string(nil), options.Communes...),
		TpTypes:  append([]string(nil), options.TpTypes...),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
