// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FilterOptions struct {
	Years    []int32  `json:"years"`
	Communes []string `json:"communes"`
	TpTypes  []string `json:"tpTypes"`
}

type InsuredUser struct {
	Nom           string  `json:"nom"`
	Prenom        string  `json:"prenom"`
	NomPere       *string `json:"nomPere,omitempty"`
	NomMere       *string `json:"nomMere,omitempty"`
	TpSolde       *int32  `json:"tpSolde,omitempty"`
	TpGenere      *int32  `json:"tpGenere,omitempty"`
	NPension      *string `json:"nPension,omitempty"`
	DateNaissance *string `json:"dateNaissance,omitempty"`
	DateDeces     *string `json:"dateDeces,omitempty"`
	TypeTp        *string `json:"typeTP,omitempty"`
	Commune       *string `json:"commune,omitempty"`
}

type Query struct {
}

type TPByMonth struct {
	Month    string `json:"month"`
	TpGenere int32  `json:"tpGenere"`
	TpSolde  int32  `json:"tpSolde"`
}

type TPSummary struct {
	TotalGenere int32 `json:"totalGenere"`
	TotalSolde  int32 `json:"totalSolde"`
}
